### ISSUE TITLE
ISSUES !!!!!!!!!!!LULXD

### ISSUE THREAD

**Issue by Egbert-Jan** [LegendaryAdresboek/Adressboek#22]
Adminpage bij soteren wordt het plaatje heel vaak herhaald en saat er niet netjes naast
Adminpage nav mooier maken
Homepage nav mooier maken
Menu balken dingen neer zetten en weg halen bijvoorbeeld about die niks doet

miss de tabel nog mooier

**Comment by Egbert-Jan** [comment]
ayyyy
bijna 
klaar

**Comment by TheBlackNarwhal** [comment]
dikke mik

**Comment by Egbert-Jan** [comment]
lel

**Comment by Egbert-Jan** [comment]
ayyy

**Comment by Egbert-Jan** [comment]
lel
