### ISSUE TITLE
Login page visual bug

### ISSUE THREAD

**Issue by TheBlackNarwhal** [LegendaryAdresboek/Adressboek#5]
Visual bug in login page, textboxes are wrongly aligned.
![image](https://cloud.githubusercontent.com/assets/26217508/23768522/a0b4fc5e-050c-11e7-9078-dea2aca29c29.png)

**Comment by Egbert-Jan** [comment]
poep

**Comment by TheBlackNarwhal** [comment]
Fixed, mocht je toch de oude versie zien, herlaad dan met cache verwijderen door: ctrl + shift + i, en dan de reload knop ingeklikt te houden.

**Comment by Egbert-Jan** [comment]
Hoe ziet hij er nu uit dan ?

**Comment by TheBlackNarwhal** [comment]
goed genoeg voor nu
![image](https://cloud.githubusercontent.com/assets/26217508/23836137/d7d9fce8-0773-11e7-975d-3b2e233c3282.png)
